[package]
name = "sysexits"
version = "0.1.0"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.61.0"
description = "The system exit codes as defined by <sysexits.h>"
documentation = "https://docs.rs/sysexits"
readme = "README.md"
repository = "https://github.com/sorairolake/sysexits-rs"
license = "Apache-2.0 OR MIT"
keywords = ["exitcode", "sysexits"]
categories = ["command-line-interface", "os"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
